name: Hiring IT Co-op Students
favicon: null
layout_spectrum: 0.387152984039858
typography_spectrum: 0.3245181532111019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8548198419157416
  lightness: 0.08152152970433235
  saturation: 0.7153738224878907
  rhythmicContrast: 0.8425775577779859
purpose: []
